/**
 * Node module customization hook for unrift module mocking (Tier A).
 *
 * Registered by `bin/unrift.mjs` via `module.register()`. Runs in a
 * worker thread (Node 20.6+ / 18.19+ behavior). Communicates with the
 * main thread via a `MessagePort` to learn which specs have been mocked.
 *
 * Why we use `receiveMessageOnPort()` instead of `port.on("message")`:
 * the resolve hook runs synchronously from the perspective of the
 * import pipeline, but Worker `MessagePort` listeners are async.
 * `receiveMessageOnPort()` (Node 18.7+) drains pending messages
 * synchronously so registrations posted from the main thread are
 * visible by the time the corresponding `await import(spec)` reaches
 * us.
 *
 * The generated synthetic module source runs back in the MAIN thread
 * (Node's loader output is evaluated in the importing thread, not the
 * loader thread). That source reads exports from `globalThis.__unriftMocks`,
 * which the main thread populates in `mock.doMock()`.
 *
 * Source compiled by tsc and shipped at `dist/esm/mock/module-loader.js`.
 */

import { receiveMessageOnPort, type MessagePort } from "node:worker_threads";

import {
  type LoaderMessage,
  MOCKS_GLOBAL_KEY,
  MOCK_URL_PREFIX,
} from "./module";

interface InitializeData {
  port: MessagePort;
}

interface Registration {
  registrationId: number;
  exportKeys: readonly string[];
}

// Loader-thread state. Populated by `initialize()` and updated by
// drainMessages() on every resolve() call.
let loaderPort: MessagePort | undefined;
const registered = new Map<string, Registration>();

/**
 * Pull every pending message off the port synchronously. Called at the
 * top of every resolve() and load() hook so the loader's view of the
 * registry is always current.
 */
function drainMessages(): void {
  if (!loaderPort) return;

  let received = receiveMessageOnPort(loaderPort);
  while (received !== undefined) {
    const message = received.message as LoaderMessage;
    if (message.type === "register") {
      registered.set(message.spec, {
        registrationId: message.registrationId,
        exportKeys: message.exportKeys,
      });
    } else if (message.type === "unregister") {
      registered.delete(message.spec);
    }
    received = receiveMessageOnPort(loaderPort);
  }
}

/**
 * Generate ESM source for a mocked spec. The source executes in the
 * MAIN thread (not the loader thread) - that's where the actual mock
 * object lives, keyed in `globalThis.__unriftMocks`.
 *
 * Pure function so future tiers can reuse this for hoisted (Tier B)
 * and relative (Tier C) mocks without rewriting the emitter.
 */
export function generateMockSource(
  spec: string,
  exportKeys: readonly string[],
): string {
  const specJson = JSON.stringify(spec);
  const lines: string[] = [
    `// Generated by unrift module mocking - do not edit.`,
    `const __mocks = globalThis[${JSON.stringify(MOCKS_GLOBAL_KEY)}];`,
    `if (!__mocks || !__mocks.has(${specJson})) {`,
    `  throw new Error(`,
    `    "Unrift module mock registry is missing the entry for " + ${specJson} + ". " +`,
    `    "This usually means mock.unmock() ran between registration and import."`,
    `  );`,
    `}`,
    `const __exports = __mocks.get(${specJson});`,
  ];

  for (const key of exportKeys) {
    if (key === "default") {
      lines.push(`export default __exports.default;`);
    } else {
      lines.push(`export const ${key} = __exports[${JSON.stringify(key)}];`);
    }
  }

  return lines.join("\n");
}

/** Node hook: called once when the loader is registered. */
export function initialize(data: InitializeData): void {
  loaderPort = data.port;
}

interface ResolveContext {
  conditions: readonly string[];
  importAttributes?: Record<string, string>;
  parentURL?: string;
}

interface ResolveResult {
  url: string;
  format?: string;
  shortCircuit?: boolean;
  importAttributes?: Record<string, string>;
}

type DefaultResolve = (
  specifier: string,
  context: ResolveContext,
) => ResolveResult | Promise<ResolveResult>;

/** Node hook: short-circuit mocked specs to a `unrift-mock:` URL. */
export async function resolve(
  specifier: string,
  context: ResolveContext,
  nextResolve: DefaultResolve,
): Promise<ResolveResult> {
  drainMessages();

  const entry = registered.get(specifier);
  if (entry) {
    // Embed the registration ID in the URL so Node's URL-keyed module
    // cache treats each re-mock of the same spec as a fresh module.
    return {
      url: `${MOCK_URL_PREFIX}${specifier}?v=${entry.registrationId}`,
      format: "module",
      shortCircuit: true,
    };
  }

  return nextResolve(specifier, context);
}

interface LoadContext {
  format?: string;
  importAttributes?: Record<string, string>;
  conditions?: readonly string[];
}

interface LoadResult {
  format: string;
  source?: string | ArrayBuffer | Uint8Array;
  shortCircuit?: boolean;
}

type DefaultLoad = (
  url: string,
  context: LoadContext,
) => LoadResult | Promise<LoadResult>;

/** Node hook: emit synthetic ESM source for mocked specs. */
export async function load(
  url: string,
  context: LoadContext,
  nextLoad: DefaultLoad,
): Promise<LoadResult> {
  if (url.startsWith(MOCK_URL_PREFIX)) {
    drainMessages();

    // URL shape: `unrift-mock:<spec>?v=<registrationId>`
    const withoutPrefix = url.slice(MOCK_URL_PREFIX.length);
    const queryIdx = withoutPrefix.indexOf("?");
    const spec =
      queryIdx === -1 ? withoutPrefix : withoutPrefix.slice(0, queryIdx);

    const entry = registered.get(spec);

    if (!entry) {
      // The user called mock.unmock() between resolve() and load().
      // Fall through to the real module so the import still works.
      return nextLoad(spec, context);
    }

    return {
      format: "module",
      source: generateMockSource(spec, entry.exportKeys),
      shortCircuit: true,
    };
  }

  return nextLoad(url, context);
}
